---
# The variables file used by the playbooks in the dbservers group.
# These don't have to be explicitly imported by vars_files: they are autopopulated.

extra_notes_motd: |
  echo "NOTES :"
  echo "Redirect port 80 et 443 au niveau du controlleur LXD"
  echo "* lxc config device add RWEB-1 HTTPS proxy listen=tcp:0.0.0.0:443 connect=tcp:localhost:443"
  echo "* lxc config device add RWEB-1 HTTP proxy listen=tcp:0.0.0.0:80 connect=tcp:localhost:80"
