---
# The variables file used by the playbooks in the dbservers group.
# These don't have to be explicitly imported by vars_files: they are autopopulated.

extra_notes_motd: |
  echo "NOTES :"
  echo "Redirect port 1194 au niveau du controlleur LXD"
  echo "* lxc config device add VPN-1 VPN proxy listen=tcp:0.0.0.0:1194 connect=tcp:localhost:1194"
